<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Mobs/Skeleton Crew/Skeleton - Warrior/Death/Death-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Mobs_Skeleton_Crew_Skeleton_-_Warrior_Death_Death-Sheet" tilewidth="48" tileheight="48" tilecount="8" columns="8">
 <image source="../../Pixel Crawler/Entities/Mobs/Skeleton Crew/Skeleton - Warrior/Death/Death-Sheet.png" width="384" height="48"/>
</tileset>
