<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Npc's/Knight/Death/Death-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Npcs_Knight_Death_Death-Sheet" tilewidth="32" tileheight="32" tilecount="9" columns="9">
 <image source="../../Pixel Crawler/Entities/Npc's/Knight/Death/Death-Sheet.png" width="288" height="32"/>
</tileset>
