<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Characters/Body_A/Animations/Idle_Base/Idle_Side-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Characters_Body_A_Animations_Idle_Base_Idle_Side-Sheet" tilewidth="64" tileheight="64" tilecount="4" columns="4">
 <image source="../../Pixel Crawler/Entities/Characters/Body_A/Animations/Idle_Base/Idle_Side-Sheet.png" width="256" height="64"/>
</tileset>
