<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Npc's/Citizen_F/Tavern_B/Idle/Idle_Side-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Npcs_Citizen_F_Tavern_B_Idle_Idle_Side-Sheet" tilewidth="64" tileheight="64" tilecount="4" columns="4">
 <image source="../../Pixel Crawler/Entities/Npc's/Citizen_F/Tavern_B/Idle/Idle_Side-Sheet.png" width="256" height="64"/>
</tileset>
