<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Mobs/Orc Crew/Orc - Shaman/Death/Death-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Mobs_Orc_Crew_Orc_-_Shaman_Death_Death-Sheet" tilewidth="64" tileheight="64" tilecount="7" columns="7">
 <image source="../../Pixel Crawler/Entities/Mobs/Orc Crew/Orc - Shaman/Death/Death-Sheet.png" width="448" height="64"/>
</tileset>
