<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Mobs/Orc Crew/Orc - Warrior/Death/Death-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Mobs_Orc_Crew_Orc_-_Warrior_Death_Death-Sheet" tilewidth="16" tileheight="16" tilecount="180" columns="36">
 <image source="../../Pixel Crawler/Entities/Mobs/Orc Crew/Orc - Warrior/Death/Death-Sheet.png" width="576" height="80"/>
</tileset>
