<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Characters/Body_A/Animations/Watering_Base/Watering_Down-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Characters_Body_A_Animations_Watering_Base_Watering_Down-Sheet" tilewidth="64" tileheight="64" tilecount="8" columns="8">
 <image source="../../Pixel Crawler/Entities/Characters/Body_A/Animations/Watering_Base/Watering_Down-Sheet.png" width="512" height="64"/>
</tileset>
