<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Characters/Body_A/Animations/Carry_Run/Carry_Run_Up-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Characters_Body_A_Animations_Carry_Run_Carry_Run_Up-Sheet" tilewidth="64" tileheight="64" tilecount="6" columns="6">
 <image source="../../Pixel Crawler/Entities/Characters/Body_A/Animations/Carry_Run/Carry_Run_Up-Sheet.png" width="384" height="64"/>
</tileset>
