<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Mobs/Skeleton Crew/Skeleton - Warrior/Idle/Idle-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Mobs_Skeleton_Crew_Skeleton_-_Warrior_Idle_Idle-Sheet" tilewidth="32" tileheight="32" tilecount="4" columns="4">
 <image source="../../Pixel Crawler/Entities/Mobs/Skeleton Crew/Skeleton - Warrior/Idle/Idle-Sheet.png" width="128" height="32"/>
</tileset>
