<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Npc's/Wizzard/Death/Death-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Npcs_Wizzard_Death_Death-Sheet" tilewidth="32" tileheight="32" tilecount="12" columns="12">
 <image source="../../Pixel Crawler/Entities/Npc's/Wizzard/Death/Death-Sheet.png" width="384" height="32"/>
</tileset>
