<?xml version="1.0" encoding="UTF-8"?>
<!-- Entities/Mobs/Orc Crew/Orc - Rogue/Run/Run-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Entities_Mobs_Orc_Crew_Orc_-_Rogue_Run_Run-Sheet" tilewidth="64" tileheight="64" tilecount="6" columns="6">
 <image source="../../Pixel Crawler/Entities/Mobs/Orc Crew/Orc - Rogue/Run/Run-Sheet.png" width="384" height="64"/>
</tileset>
