<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Cooking Station/Cooker/Cooker_03-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Cooking_Station_Cooker_Cooker_03-Sheet" tilewidth="32" tileheight="32" tilecount="6" columns="6">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Cooking Station/Cooker/Cooker_03-Sheet.png" width="192" height="32"/>
</tileset>
