<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Sawmill/Level_2-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Sawmill_Level_2-Sheet" tilewidth="16" tileheight="16" tilecount="1280" columns="40">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Sawmill/Level_2-Sheet.png" width="640" height="512"/>
</tileset>
