<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Tilesets/Wall_Variations.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Tilesets_Wall_Variations" tilewidth="16" tileheight="16" tilecount="480" columns="16">
 <image source="../../Pixel Crawler/Environment/Tilesets/Wall_Variations.png" width="256" height="480"/>
</tileset>
