<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Props/Static/Trees/Model_01/Size_03.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Props_Static_Trees_Model_01_Size_03" tilewidth="16" tileheight="16" tilecount="156" columns="13">
 <image source="../../Pixel Crawler/Environment/Props/Static/Trees/Model_01/Size_03.png" width="208" height="192"/>
</tileset>
