<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Props/Static/Trees/Model_01/Size_02.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Props_Static_Trees_Model_01_Size_02" tilewidth="128" tileheight="128" tilecount="2" columns="2">
 <image source="../../Pixel Crawler/Environment/Props/Static/Trees/Model_01/Size_02.png" width="256" height="128"/>
</tileset>
