<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Cooking Station/Grill/Grill_03-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Cooking_Station_Grill_Grill_03-Sheet" tilewidth="64" tileheight="64" tilecount="4" columns="4">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Cooking Station/Grill/Grill_03-Sheet.png" width="256" height="64"/>
</tileset>
