<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Furnace/Iron_02-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Furnace_Iron_02-Sheet" tilewidth="16" tileheight="16" tilecount="48" columns="6">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Furnace/Iron_02-Sheet.png" width="96" height="128"/>
</tileset>
