<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Anvil/Anvil_01-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Anvil_Anvil_01-Sheet" tilewidth="16" tileheight="16" tilecount="800" columns="32">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Anvil/Anvil_01-Sheet.png" width="512" height="400"/>
</tileset>
