<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Sawmill/Level_1.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Sawmill_Level_1" tilewidth="16" tileheight="16" tilecount="4" columns="2">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Sawmill/Level_1.png" width="32" height="32"/>
</tileset>
