<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Props/Static/Pan.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Props_Static_Pan" tilewidth="16" tileheight="16" tilecount="110" columns="10">
 <image source="../../Pixel Crawler/Environment/Props/Static/Pan.png" width="160" height="176"/>
</tileset>
