<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Sawmill/Base.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Sawmill_Base" tilewidth="16" tileheight="16" tilecount="144" columns="16">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Sawmill/Base.png" width="256" height="144"/>
</tileset>
