<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Props/Static/Rocks.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Props_Static_Rocks" tilewidth="16" tileheight="16" tilecount="247" columns="13">
 <image source="../../Pixel Crawler/Environment/Props/Static/Rocks.png" width="208" height="304"/>
</tileset>
