<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Props/Static/Trees/Model_01/Size_04.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Props_Static_Trees_Model_01_Size_04" tilewidth="16" tileheight="16" tilecount="368" columns="23">
 <image source="../../Pixel Crawler/Environment/Props/Static/Trees/Model_01/Size_04.png" width="368" height="256"/>
</tileset>
