<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Tilesets/Floors_Tiles.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Tilesets_Floors_Tiles" tilewidth="16" tileheight="16" tilecount="650" columns="25">
 <image source="../../Pixel Crawler/Environment/Tilesets/Floors_Tiles.png" width="400" height="416"/>
</tileset>
