<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Alchemy/Alchemy_Table_03-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Alchemy_Alchemy_Table_03-Sheet" tilewidth="16" tileheight="16" tilecount="625" columns="25">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Alchemy/Alchemy_Table_03-Sheet.png" width="400" height="400"/>
</tileset>
