<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Anvil/Anvil.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Anvil_Anvil" tilewidth="16" tileheight="16" tilecount="170" columns="17">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Anvil/Anvil.png" width="272" height="160"/>
</tileset>
