<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Props/Animated/Pan_03-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Props_Animated_Pan_03-Sheet" tilewidth="32" tileheight="32" tilecount="12" columns="12">
 <image source="../../Pixel Crawler/Environment/Props/Animated/Pan_03-Sheet.png" width="384" height="32"/>
</tileset>
