<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Sawmill/Level_3-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Sawmill_Level_3-Sheet" tilewidth="16" tileheight="16" tilecount="2240" columns="56">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Sawmill/Level_3-Sheet.png" width="896" height="640"/>
</tileset>
