<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Buildings/Walls.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Buildings_Walls" tilewidth="16" tileheight="16" tilecount="2100" columns="42">
 <image source="../../Pixel Crawler/Environment/Structures/Buildings/Walls.png" width="672" height="800"/>
</tileset>
