<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Cooking Station/Estructure.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Cooking_Station_Estructure" tilewidth="16" tileheight="16" tilecount="252" columns="18">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Cooking Station/Estructure.png" width="288" height="224"/>
</tileset>
