<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Bonfire/Bonfire_09-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Bonfire_Bonfire_09-Sheet" tilewidth="32" tileheight="32" tilecount="10" columns="10">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Bonfire/Bonfire_09-Sheet.png" width="320" height="32"/>
</tileset>
