<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Cooking Station/Butchery/Butchery_04.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Cooking_Station_Butchery_Butchery_04" tilewidth="16" tileheight="16" tilecount="25" columns="5">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Cooking Station/Butchery/Butchery_04.png" width="80" height="80"/>
</tileset>
