<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Props/Static/Trees/Model_03/Size_05.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Props_Static_Trees_Model_03_Size_05" tilewidth="16" tileheight="16" tilecount="768" columns="24">
 <image source="../../Pixel Crawler/Environment/Props/Static/Trees/Model_03/Size_05.png" width="384" height="512"/>
</tileset>
