<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Structures/Stations/Furnace/Bricks_01-Sheet.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Structures_Stations_Furnace_Bricks_01-Sheet" tilewidth="16" tileheight="16" tilecount="24" columns="4">
 <image source="../../Pixel Crawler/Environment/Structures/Stations/Furnace/Bricks_01-Sheet.png" width="64" height="96"/>
</tileset>
