<?xml version="1.0" encoding="UTF-8"?>
<!-- Environment/Props/Static/Furniture.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Environment_Props_Static_Furniture" tilewidth="16" tileheight="16" tilecount="2700" columns="50">
 <image source="../../Pixel Crawler/Environment/Props/Static/Furniture.png" width="800" height="864"/>
</tileset>
