<?xml version="1.0" encoding="UTF-8"?>
<!-- MockUps/Tavern.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="MockUps_Tavern" tilewidth="16" tileheight="16" tilecount="6400" columns="80">
 <image source="../../Pixel Crawler/MockUps/Tavern.png" width="1280" height="1280"/>
</tileset>
