<?xml version="1.0" encoding="UTF-8"?>
<!-- Weapons/Wood/Wood.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Weapons_Wood_Wood" tilewidth="16" tileheight="16" tilecount="84" columns="12">
 <image source="../../Pixel Crawler/Weapons/Wood/Wood.png" width="192" height="112"/>
</tileset>
