<?xml version="1.0" encoding="UTF-8"?>
<!-- Weapons/Hands/Hands.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Weapons_Hands_Hands" tilewidth="16" tileheight="16" tilecount="12" columns="2">
 <image source="../../Pixel Crawler/Weapons/Hands/Hands.png" width="32" height="96"/>
</tileset>
