<?xml version="1.0" encoding="UTF-8"?>
<!-- Weapons/Bone/Bone.png — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="Weapons_Bone_Bone" tilewidth="16" tileheight="16" tilecount="126" columns="14">
 <image source="../../Pixel Crawler/Weapons/Bone/Bone.png" width="224" height="144"/>
</tileset>
