#!/usr/bin/env python3
"""Import the whole Pixel Crawler pack as Tiled tilesets.

    python3 tools/import-pixelcrawler.py

Writes one .tsx per PNG into Maps/Tilesets/PixelCrawler/, mirroring the pack's
folder structure in the file name. Every tileset REFERENCES its PNG in place —
nothing is copied, sliced or rescaled.

Tile size: the pack is a native 16px grid, so that is the default. Animation
strips (a row of frames, e.g. 384x64) are given their real frame size instead, so
they open in Tiled as frames rather than as sixteenths of a frame.

These are the LIBRARY, for authoring: open any of them in Tiled with
"Add External Tileset". The short-named tilesets in Maps/Tilesets/ (Floors, Water,
Walls, IntProps, …) are the ones the maps actually reference; a couple therefore
point at the same PNG as a file here, which is harmless.
"""
from PIL import Image
import os, glob, xml.sax.saxutils as sx

ROOT = "src/AlfarQuest.Client/wwwroot"
PC = os.path.join(ROOT, "Maps/Pixel Crawler")
OUT = os.path.join(ROOT, "Maps/Tilesets/PixelCrawler")
T = 16

os.makedirs(OUT, exist_ok=True)

def tile_size(w, h, name):
    """A strip of square-ish frames keeps its frame size; everything else is 16px.
    Guarded so a 400x400 sheet is not mistaken for one enormous frame."""
    if h <= 128 and w % h == 0 and w // h >= 2:
        return h, h
    return T, T

made, frames, skipped = 0, 0, []
index = []
for path in sorted(glob.glob(os.path.join(PC, "**", "*.png"), recursive=True)):
    rel = os.path.relpath(path, PC)
    try:
        w, h = Image.open(path).size
    except Exception as e:
        skipped.append((rel, str(e))); continue

    tw, th = tile_size(w, h, rel)
    if w % tw or h % th:
        skipped.append((rel, f"{w}x{h} does not divide by {tw}x{th}")); continue

    cols, rows = w // tw, h // th
    name = os.path.splitext(rel)[0].replace(os.sep, "_").replace(" ", "_").replace("'", "")
    src = os.path.relpath(path, OUT).replace(os.sep, "/")
    with open(os.path.join(OUT, name + ".tsx"), "w") as f:
        f.write(f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- {sx.escape(rel)} — Pixel Crawler, referenced in place. Generated by
     tools/import-pixelcrawler.py; do not hand-edit, re-run it instead. -->
<tileset version="1.10" tiledversion="1.10.2" name="{name}" tilewidth="{tw}" tileheight="{th}" tilecount="{cols*rows}" columns="{cols}">
 <image source="{sx.escape(src)}" width="{w}" height="{h}"/>
</tileset>
''')
    made += 1
    if (tw, th) != (T, T): frames += 1
    index.append((name, rel, f"{w}x{h}", f"{tw}x{th}", cols * rows))

# A readable index, so the library can be browsed without opening Tiled.
with open(os.path.join(OUT, "INDEX.md"), "w") as f:
    f.write("# Pixel Crawler tileset library\n\n")
    f.write("Generated by `tools/import-pixelcrawler.py`. One tileset per PNG, each\n"
            "referencing the art in place. Open any of these in Tiled with\n"
            "**Add External Tileset**.\n\n")
    f.write("| tileset | source | image | tile | tiles |\n|---|---|---|---|---|\n")
    for name, rel, size, tile, n in index:
        f.write(f"| `{name}.tsx` | {rel} | {size} | {tile} | {n} |\n")

print(f"wrote {made} tilesets to {OUT}  ({frames} with real animation-frame sizes)")
if skipped:
    print(f"skipped {len(skipped)}:")
    for rel, why in skipped[:10]:
        print(f"   {rel}: {why}")
